mod common;
use docconvert::{config::*,convert,model::*};
#[test]fn text_and_markdown_conversion(){let t=common::Temp::new();let input=t.write("a.txt",b"hello");let opts=Options{format_choice:FormatChoice::Md,output:Some(t.0.join("out")),..Options::default()};let r=convert::convert_file(&input,&opts).unwrap();assert_eq!(r.status,"converted");assert_eq!(std::fs::read_to_string(t.0.join("out/a.md")).unwrap(),"hello\n");let r=convert::convert_file(&input,&opts).unwrap();assert!(r.status.starts_with("skipped"));let p=t.write("b.md",b"# Title\n\n**bold**");let o=Options{format_choice:FormatChoice::Txt,..opts};convert::convert_file(&p,&o).unwrap();assert!(std::fs::read_to_string(t.0.join("out/b.txt")).unwrap().contains("TITLE"))}
#[test]fn markdown_passthrough(){let t=common::Temp::new();let bytes=b"odd  spacing\r\n\r\n<x>raw</x>\n";let p=t.write("a.md",bytes);let o=Options{format_choice:FormatChoice::Md,output:Some(t.0.join("out")),..Options::default()};convert::convert_file(&p,&o).unwrap();assert_eq!(std::fs::read(t.0.join("out/a.md")).unwrap(),bytes)}
#[test]fn html_asset_and_preview(){let t=common::Temp::new();t.write("p.png",&common::png());let p=t.write("a.html",br#"<!doctype html><HTML><BODY><NAV>Remove me</NAV><SCRIPT>danger()</SCRIPT><h1>Article</h1><ul><li>One<ul><li>Two</li></ul></li></ul><table><tr><th colspan="2">Header</th></tr><tr><td>a</td><td>b</td></tr></table><figure><img src="p.png" alt="image"><figcaption>Caption</figcaption></figure><p><strong>Bold</strong> &copy; text</p></BODY></HTML>"#);let opts=Options{output:Some(t.0.join("out")),..Options::default()};let preview=convert::preview(&p,&opts).unwrap();assert!(preview.contains("Images:      1"));assert!(!t.0.join("out").exists());let r=convert::convert_file(&p,&opts).unwrap();assert_eq!(r.images,1);let s=std::fs::read_to_string(t.0.join("out/a.md")).unwrap();assert!(!s.contains("danger()"));assert!(!s.contains("Remove me"));assert!(s.contains("Caption"));assert!(t.0.join("out/assets/a/image-001.png").exists());let json=std::fs::read_to_string(t.0.join("out/a.report.json")).unwrap();assert!(serde_json::from_str::<serde_json::Value>(&json).is_ok())}
#[test]fn html_malformed_and_remote_image(){let t=common::Temp::new();let p=t.write("a.html",b"<html><body><p>kept<img src='https://example.org/p.png'>");let d=common::extract(&p);assert!(d.text_len()>0);assert!(d.assets.is_empty());assert!(!d.warnings.is_empty())}
#[test]fn refuses_source_overwrite(){let t=common::Temp::new();let p=t.write("a.md",b"original");let o=Options{overwrite:true,format_choice:FormatChoice::Md,..Options::default()};assert!(convert::convert_file(&p,&o).is_err());assert_eq!(std::fs::read(&p).unwrap(),b"original")}
#[test]fn cli_usage_and_unknown_exit(){let t=common::Temp::new();let exe=env!("CARGO_BIN_EXE_docconvert");assert_eq!(std::process::Command::new(exe).status().unwrap().code(),Some(2));let p=t.write("unknown.bin",b"\0\xff\0\xfe");let r=std::process::Command::new(exe).arg(p).output().unwrap();assert_eq!(r.status.code(),Some(1));assert!(String::from_utf8_lossy(&r.stderr).contains("unknown file format"))}
#[test]fn cli_precedence_all_layers(){let t=common::Temp::new();let p=t.write("a.txt",b"plain");let c=t.write("config",b"format = md\n");let r=std::process::Command::new(env!("CARGO_BIN_EXE_docconvert")).arg(&p).args(["--profile","plain","--config"]).arg(&c).args(["--format","txt","--output"]).arg(t.0.join("out")).status().unwrap();assert!(r.success());assert!(t.0.join("out/a.txt").exists())}
#[test]fn zero_byte_input_error(){let t=common::Temp::new();let p=t.write("empty.txt",b"");assert!(convert::preview(&p,&Options::default()).is_err())}
#[test]fn size_guard_precedes_parsing(){let t=common::Temp::new();let p=t.write("a.docx",b"garbage");assert!(convert::preview(&p,&Options{max_file_bytes:1,..Options::default()}).unwrap_err().to_string().contains("file exceeds --max-size"))}
#[test]fn no_formulas_configuration(){let mut o=Options::default();o.set("no-formulas","true").unwrap();assert!(!o.preserve_formulas);let _=Meta::default();}
#[test]fn bare_filename_in_cwd_converts(){// Release audit: bare CWD-relative names failed ("entity not found") for loader formats.
let t=common::Temp::new();std::fs::write(t.0.join("a.md"),b"# Hi\n").unwrap();let exe=env!("CARGO_BIN_EXE_docconvert");let st=std::process::Command::new(exe).current_dir(&t.0).args(["a.md","-f","md","-o","out"]).status().unwrap();assert!(st.success());assert!(t.0.join("out/a.md").exists());std::fs::write(t.0.join("c.md"),b"# Hi\n").unwrap();let st=std::process::Command::new(exe).current_dir(&t.0).args(["c.md"]).status().unwrap();assert!(st.success());assert!(t.0.join("c.txt").exists())}
#[test]fn long_stem_shortens_asset_namespace(){let t=common::Temp::new();t.write("p.png",&common::png());let stem="word ".repeat(30);let p=t.write(&format!("{stem}.html"),b"<html><body><img src=\"p.png\" alt=\"image\"></body></html>");let opts=Options{output:Some(t.0.join("out")),..Options::default()};let r=convert::convert_file(&p,&opts).unwrap();assert_eq!(r.status,"converted");assert!(r.warnings.iter().any(|w|w.contains("shortened in asset paths")));let mut names=std::fs::read_dir(t.0.join("out/assets")).unwrap().map(|e|e.unwrap().file_name().into_string().unwrap()).collect::<Vec<_>>();assert_eq!(names.len(),1);let ns=names.pop().unwrap();assert!(ns.starts_with("long-"),"{ns}");assert!(ns.len()<=200);assert!(t.0.join("out/assets").join(&ns).join("image-001.png").exists());assert!(r.assets.iter().all(|a|a.starts_with(&format!("assets/{ns}/"))))}
