mod common;
use docconvert::{assets::AssetManager,config::*,extract::{text,csv,package},model::*,render::{self,OutFormat}};
#[test]fn asset_dedupe_and_names(){let mut a=AssetManager::default();let first=a.add(common::png(),"test",None);assert_eq!(first,a.add(common::png(),"duplicate",None));assert_eq!(a.assets.len(),1);let id=a.add(b"other".to_vec(),"test",None);assert_eq!(a.assets[id].filename,"image-002.bin");let t=common::Temp::new();assert_eq!(a.write_all(&t.0).unwrap(),2);assert!(t.0.join("assets/image-001.png").exists())}
#[test]fn txt_paragraphs(){let d=text::extract_txt(b"one\r\n\r\ntwo",Meta::default());assert_eq!(d.blocks.len(),2)}
#[test]fn markdown_semantics(){let d=text::extract_markdown(b"# Title\n\n- one\n  - two\n\n|a\\|b|c|\n|---|---:|\n|x|y|\n\n***both*** [^1]\n\n[^1]: note",Meta::default());assert_eq!(d.footnotes.len(),1);assert!(d.blocks.iter().any(|b|matches!(b,Block::Table(_))));let s=render::markdown::render_markdown(&d,false);assert!(s.contains("a\\|b"));assert!(s.contains("[^1]: note"));assert!(s.contains("***both***"))}
#[test]fn unclosed_markers_preserved(){for s in ["*","**","***","[x](","![x]","`","~~","$","[^","\\"]{let d=text::extract_markdown(s.as_bytes(),Meta::default());assert!(!d.blocks.is_empty())}let d=text::extract_markdown(b"```rust\nx",Meta::default());assert!(d.warnings.iter().any(|w|w.contains("unclosed fence")))}
#[test]fn csv_quotes_and_large_sheet(){let d=csv::extract_csv(b"name,value\n\"a,b\",\"line1\nline2\"\n\n",Meta::default(),b',',&Options::default());let w=d.workbook.unwrap();assert_eq!(w.sheets[0].cells[&(1,0)].display,"a,b");assert_eq!(w.sheets[0].cells[&(1,1)].display,"line1\nline2");let s=(0..300).map(|n|format!("{n},text\n")).collect::<String>();let d=csv::extract_csv(s.as_bytes(),Meta::default(),b',',&Options::default());assert!(d.blocks.iter().any(|b|matches!(b,Block::CodeBlock{..})));assert!(!d.warnings.is_empty())}
#[test]fn tsv_number_display(){let d=csv::extract_csv(b"n\tt\n001\tx",Meta::default(),b'\t',&Options::default());assert_eq!(d.workbook.unwrap().sheets[0].cells[&(1,0)].display,"001")}
#[test]fn profiles_and_config_precedence(){let t=common::Temp::new();let p=t.write("config",b"format = md\ninclude-notes = true\n");let mut o=Options::default();o.apply_profile("plain").unwrap();o.load_config_file(&p).unwrap();assert_eq!(o.format_choice,FormatChoice::Md);assert!(o.include_notes);assert!(o.set("formta","md").unwrap_err().to_string().contains("format"));for profile in ["academic","technical","plain","spreadsheet","archive","accessibility","tts","ocr","strict"]{Options::default().apply_profile(profile).unwrap()}}
#[test]fn auto_choice(){let d=text::extract_txt(b"plain text",Meta::default());assert_eq!(render::choose_output(&d,FormatChoice::Auto).0,OutFormat::Txt);let d=csv::extract_csv(b"a,b\n1,2",Meta::default(),b',',&Options::default());assert_eq!(render::choose_output(&d,FormatChoice::Auto).0,OutFormat::Md);assert_eq!(render::choose_output(&d,FormatChoice::Txt).1,"user-specified")}
#[test]fn placeholder_honest_stub(){let mut d=Document::new("t",Format::Unknown);d.blocks.push(Block::Placeholder{kind:PlaceholderKind::Chart,label:Some("Q".into()),asset:None});let md=render::markdown::render_markdown(&d,false);assert!(md.contains("no rendered asset available"),"{md}");assert!(!md.contains("preserved as an external asset"),"{md}");let tx=render::txt::render_txt(&d);assert!(tx.contains("no rendered asset available"),"{tx}")}
#[test]fn reason_string_rule(){let plain=text::extract_txt(b"plain text",Meta::default());let (f,r)=render::choose_output(&plain,FormatChoice::Auto);assert_eq!(f,OutFormat::Txt);assert_eq!(r,"txt: plain text is sufficient");let mut rich=Document::new("t",Format::Csv);rich.blocks.push(Block::Table(Table{header:vec![],rows:vec![],caption:None,approximate:false}));let (f2,r2)=render::choose_output(&rich,FormatChoice::Auto);assert_eq!(f2,OutFormat::Md);assert_eq!(r2,"md: tables")}
#[test]fn package_path_guards(){assert_eq!(package::normalize("OEBPS/text","../images/a.png"),Some("OEBPS/images/a.png".into()));assert!(package::normalize("","../../outside").is_none());let bad=common::zip(&[("../evil",b"bad")]);assert!(package::Package::open(&bad).is_err())}
#[test]fn xml_depth_guard(){let s=format!("{}{}","<a>".repeat(70),"</a>".repeat(70));assert!(package::parse(s.as_bytes(),false).is_err())}
#[test]fn markdown_golden(){let d=text::extract_markdown(b"# Hello\n\nA **bold** statement.\n",Meta::default());assert_eq!(render::markdown::render_markdown(&d,false),include_str!("golden/basic.md"))}
#[test]fn txt_golden(){let d=text::extract_markdown(b"# Hello\n\nA **bold** statement.\n",Meta::default());assert_eq!(render::txt::render_txt(&d),include_str!("golden/basic.txt"))}
#[test]fn empty_link_target_renders_bare_text(){let link=Inline::Link{children:vec![Inline::Text("cover".into())],url:String::new()};let mut d=Document::new("t",Format::Unknown);d.blocks.push(Block::Paragraph(vec![link]));let md=render::markdown::render_markdown(&d,false);assert!(!md.contains("[]()"),"{md}");assert!(md.contains("cover"),"{md}");let tx=render::txt::render_txt(&d);assert!(!tx.contains("()"),"{tx}");assert!(tx.contains("cover"),"{tx}")}
