mod common;
use docconvert::{config::*,convert,model::*,render};
#[test]fn xlsx_formula_preservation_end_to_end(){let t=common::Temp::new();let p=t.write("book.xlsx",&common::xlsx());let o=Options{format_choice:FormatChoice::Md,output:Some(t.0.join("out")),..Options::default()};let r=convert::convert_file(&p,&o).unwrap();assert_eq!(r.worksheets,2);assert_eq!(r.formulas,1);let s=std::fs::read_to_string(t.0.join("out/book.md")).unwrap();assert!(s.contains("220000"));assert!(s.contains("=SUM(B2:B3)"));assert!(!s.contains("Secret sheet text"));assert!(s.contains("Formula comment"))}
#[test]fn xlsx_fidelity_and_sparse_dimensions(){let t=common::Temp::new();let d=common::extract(&t.write("a.xlsx",&common::xlsx()));let w=d.workbook.unwrap();assert_eq!(w.sheets[0].max_row,2);assert_eq!(w.sheets[0].merged,vec!["A1:B1"]);assert_eq!(w.sheets[0].cells[&(0,0)].hyperlink.as_deref(),Some("https://example.org"));assert!(w.sheets[1].hidden)}
#[test]fn hidden_sheets_can_be_included(){let t=common::Temp::new();let p=t.write("a.xlsx",&common::xlsx());let detection=docconvert::detect::detect_file(&p).unwrap();let d=docconvert::extract::extract_file(&p,&detection,&Options{include_hidden_sheets:true,..Options::default()}).unwrap();assert!(render::markdown::render_markdown(&d,false).contains("Secret sheet text"))}
#[test]fn ods_formula_verbatim(){let t=common::Temp::new();let d=common::extract(&t.write("a.ods",&common::ods()));let w=d.workbook.as_ref().unwrap();assert_eq!(w.sheets[0].cells[&(1,0)].formula.as_deref(),Some("of:=SUM([.B2:.B3])"));assert!(d.warnings.iter().any(|s|s.contains("ODF formula syntax preserved as-is")))}
#[test]fn common_lowering_formula_and_merge(){let mut sheet=Sheet{name:"Data".into(),max_row:1,max_col:1,..Sheet::default()};sheet.cells.insert((1,0),Cell{reference:"A2".into(),formula:Some("=1+1".into()),display:"2".into(),kind:CellKind::Number,..Cell::default()});let bs=docconvert::extract::sheet_blocks(&sheet,&Options::default());assert!(bs.iter().any(|b|matches!(b,Block::FormulaList(_))));let bs=docconvert::extract::sheet_blocks(&sheet,&Options{preserve_formulas:false,..Options::default()});assert!(!bs.iter().any(|b|matches!(b,Block::FormulaList(_))))}
#[test]fn legacy_xls_preserves_cached_formula_value(){let t=common::Temp::new();let p=t.write("legacy.xls",&common::xls());let d=common::extract(&p);let w=d.workbook.as_ref().unwrap();assert_eq!(w.sheets[0].cells[&(0,0)].display,"3");assert!(d.warnings.iter().any(|w|w.contains("legacy XLS")));let o=Options{output:Some(t.0.join("out")),format_choice:FormatChoice::Md,..Options::default()};convert::convert_file(&p,&o).unwrap();assert!(std::fs::read_to_string(t.0.join("out/legacy.md")).unwrap().contains('3'))}
#[test]fn lower_workbook_warnings_not_duplicated(){// P2-S03: read_workbook lowers, then extract_file lowers again — output is
// idempotent (blocks.clear) but the warnings must not be emitted twice.
let t=common::Temp::new();let d=common::extract(&t.write("a.xlsx",&common::xlsx()));assert_eq!(d.warnings.iter().filter(|w|*w=="1 hidden sheets skipped").count(),1)}
#[test]fn xlsx_number_format_date_converts_display(){// P2-S01: a numeric cell with a date number-format renders ISO 8601, not the raw serial.
let t=common::Temp::new();
let styles=br#"<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts><numFmt numFmtId="164" formatCode="m/d/yyyy"/></numFmts><cellXfs><xf numFmtId="164"/></cellXfs></styleSheet>"#.as_slice();
let sheet=br#"<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:D3"/><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Total</t></is></c></row><row r="2"><c r="B2" s="0"><v>44927</v></c><c r="D2"><f>SUM(B2:B3)</f><v>220000</v></c></row><row r="3"><c r="B3"><v>120000</v></c></row></sheetData></worksheet>"#.as_slice();
let bytes=common::zip_patch(&common::xlsx(),&[("xl/styles.xml",styles),("xl/worksheets/sheet8.xml",sheet)]);
let d=common::extract(&t.write("dated.xlsx",&bytes));let w=d.workbook.as_ref().unwrap();let cell=&w.sheets[0].cells[&(1,1)];assert!(matches!(cell.kind,CellKind::Date));assert_eq!(cell.display,"2023-01-01")}
#[test]fn xlsx_chart_presence_placeholder(){// P2-S02: chart presence via drawing rels → Placeholder (no asset) + inventory warning.
let t=common::Temp::new();
let rels=br#"<Relationships><Relationship Id="link" Type="hyperlink" Target="https://example.org" TargetMode="External"/><Relationship Id="comment" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/><Relationship Id="draw" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>"#.as_slice();
let drawing=br#"<xdr:wsDr xmlns:xdr="d" xmlns:c="c"><xdr:twoCellAnchor><xdr:graphicFrame><c:chart id="ch"/></xdr:graphicFrame></xdr:twoCellAnchor></xdr:wsDr>"#.as_slice();
let drawing_rels=br#"<Relationships><Relationship Id="ch" Target="../charts/chart1.xml" Type="chart"/></Relationships>"#.as_slice();
let chart=br#"<c:chartSpace xmlns:c="c"><c:chart><c:title><c:tx><c:rich><a:p xmlns:a="a"><a:r><a:t>My Chart</a:t></a:r></a:p></c:rich></c:tx></c:title></c:chart></c:chartSpace>"#.as_slice();
let bytes=common::zip_patch(&common::xlsx(),&[("xl/worksheets/_rels/sheet8.xml.rels",rels),("xl/drawings/drawing1.xml",drawing),("xl/drawings/_rels/drawing1.xml.rels",drawing_rels),("xl/charts/chart1.xml",chart)]);
let d=common::extract(&t.write("charted.xlsx",&bytes));let w=d.workbook.as_ref().unwrap();assert_eq!(w.sheets[0].charts,vec![Some("My Chart".to_string())]);assert!(d.warnings.iter().any(|s|s.contains("chart inventory")));assert!(d.blocks.iter().any(|b|matches!(b,Block::Placeholder{kind:PlaceholderKind::Chart,label:Some(_),asset:None})))}
#[test]fn xlsx_bool_and_error_kinds(){// P2-S01/P2-S05: boolean + error cells keep kind and a non-blank display.
let t=common::Temp::new();
let sheet=br#"<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:E4"/><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Total</t></is></c></row><row r="2"><c r="B2"><v>100000</v></c><c r="D2"><f>SUM(B2:B3)</f><v>220000</v></c></row><row r="3"><c r="B3"><v>120000</v></c></row><row r="4"><c r="D4" t="b"><v>0</v></c><c r="E4" t="e"><v>#DIV/0!</v></c></row></sheetData></worksheet>"#.as_slice();
let bytes=common::zip_patch(&common::xlsx(),&[("xl/worksheets/sheet8.xml",sheet)]);
let d=common::extract(&t.write("kinds.xlsx",&bytes));let w=d.workbook.as_ref().unwrap();
let b=&w.sheets[0].cells[&(3,3)];assert!(matches!(b.kind,CellKind::Bool));assert_eq!(b.display,"FALSE");
let e=&w.sheets[0].cells[&(3,4)];assert!(matches!(e.kind,CellKind::Error));assert!(!e.display.is_empty())}
#[test]fn oversized_used_range_rejected(){// §9/AD-cell-count guard: real coordinates (not declared dimension) beyond the limit → Unsupported.
let t=common::Temp::new();
let sheet=br#"<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:D3"/><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Total</t></is></c></row><row r="100000"><c r="ZZ100000"><v>1</v></c></row></sheetData></worksheet>"#.as_slice();
let bytes=common::zip_patch(&common::xlsx(),&[("xl/worksheets/sheet8.xml",sheet)]);
let p=t.write("huge.xlsx",&bytes);let detection=docconvert::detect::detect_file(&p).unwrap();
assert!(matches!(docconvert::extract::extract_file(&p,&detection,&docconvert::config::Options::default()),Err(docconvert::error::ConvertError::Unsupported(s))if s=="worksheet used range exceeds cell limit"))}
