mod common;
use docconvert::{config::*,convert,extract::{ooxml,package},model::*,render};
#[test]fn docx_heading_style_id_and_notes(){let t=common::Temp::new();let b=common::docx(r#"<w:p><w:pPr><w:pStyle w:val="Haupt"/></w:pPr><w:r><w:t>Title</w:t></w:r></w:p><w:p><w:r><w:t>Body</w:t><w:footnoteReference w:id="1"/></w:r></w:p>"#);let d=common::extract(&t.write("a.docx",&b));assert!(matches!(&d.blocks[0],Block::Heading{level:1,..}));assert_eq!(d.footnotes.len(),1);assert!(render::markdown::render_markdown(&d,false).contains("[^1]"))}
#[test]fn docx_separate_list_ids(){let t=common::Temp::new();let b=common::docx(r#"<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>one</w:t></w:r></w:p><w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="2"/></w:numPr></w:pPr><w:r><w:t>two</w:t></w:r></w:p>"#);let d=common::extract(&t.write("a.docx",&b));assert_eq!(d.blocks.iter().filter(|b|matches!(b,Block::List{..})).count(),2)}
#[test]fn docx_table_merge_and_image(){let t=common::Temp::new();let b=common::docx(r#"<w:tbl><w:tr><w:tc><w:tcPr><w:vMerge w:val="restart"/><w:gridSpan w:val="2"/></w:tcPr><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>merge</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:vMerge/><w:gridSpan w:val="2"/></w:tcPr></w:tc></w:tr></w:tbl><w:p><w:r><w:drawing><a:blip r:embed="img"/></w:drawing></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Caption"/></w:pPr><w:r><w:t>Image caption</w:t></w:r></w:p>"#);let d=common::extract(&t.write("a.docx",&b));let table=d.blocks.iter().find_map(|b|if let Block::Table(t)=b{Some(t)}else{None}).unwrap();assert_eq!(table.header[0].rowspan,2);assert_eq!(table.header[0].colspan,2);assert_eq!(d.assets.len(),1);assert!(d.blocks.iter().any(|b|matches!(b,Block::Image{caption:Some(_),..})))}
#[test]fn docx_table_bold_header_rule(){let t=common::Temp::new();let bold=common::docx(r#"<w:tbl><w:tr><w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>H</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:p><w:r><w:t>body</w:t></w:r></w:p></w:tc></w:tr></w:tbl>"#);let d=common::extract(&t.write("b.docx",&bold));let table=d.blocks.iter().find_map(|b|if let Block::Table(t)=b{Some(t)}else{None}).unwrap();assert_eq!(table.header.len(),1);let plain=common::docx(r#"<w:tbl><w:tr><w:tc><w:p><w:r><w:t>H</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:p><w:r><w:t>body</w:t></w:r></w:p></w:tc></w:tr></w:tbl>"#);let d=common::extract(&t.write("p.docx",&plain));let table=d.blocks.iter().find_map(|b|if let Block::Table(t)=b{Some(t)}else{None}).unwrap();assert!(table.header.is_empty());assert_eq!(table.rows.len(),2)}
#[test]fn omml_mappings(){for(xml,expected)in[("<m:f><m:num><m:r><m:t>a</m:t></m:r></m:num><m:den><m:r><m:t>b</m:t></m:r></m:den></m:f>","\\frac{a}{b}"),("<m:sSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSup>","{x}^{2}"),("<m:sSub><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub>","{x}_{i}"),("<m:sSubSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSubSup>","{x}_{i}^{2}"),("<m:rad><m:e><m:r><m:t>x</m:t></m:r></m:e></m:rad>","\\sqrt{x}"),("<m:rad><m:deg><m:r><m:t>3</m:t></m:r></m:deg><m:e><m:r><m:t>x</m:t></m:r></m:e></m:rad>","\\sqrt[3]{x}"),("<m:nary><m:naryPr><m:chr m:val=\"∫\"/></m:naryPr><m:sub><m:r><m:t>a</m:t></m:r></m:sub><m:sup><m:r><m:t>b</m:t></m:r></m:sup><m:e><m:r><m:t>x</m:t></m:r></m:e></m:nary>","\\int_{a}^{b}{x}"),("<m:d><m:dPr><m:begChr m:val=\"[\"/><m:endChr m:val=\"]\"/></m:dPr><m:e><m:r><m:t>x</m:t></m:r></m:e></m:d>","\\left[x\\right]"),("<m:m><m:mr><m:e><m:r><m:t>a</m:t></m:r></m:e><m:e><m:r><m:t>b</m:t></m:r></m:e></m:mr><m:mr><m:e><m:r><m:t>c</m:t></m:r></m:e><m:e><m:r><m:t>d</m:t></m:r></m:e></m:mr></m:m>","\\begin{matrix}a & b \\\\ c & d\\end{matrix}"),("<m:acc><m:accPr><m:chr m:val=\"^\"/></m:accPr><m:e><m:r><m:t>x</m:t></m:r></m:e></m:acc>","\\hat{x}")]{let(root,_)=package::parse(xml.as_bytes(),false).unwrap();let node=root.children().next().unwrap();assert_eq!(ooxml::omml_to_latex(&node,&mut vec![]),expected)}let(root,_)=package::parse(b"<m:unknown>retained</m:unknown>",false).unwrap();let mut warnings=vec![];assert_eq!(ooxml::omml_to_latex(&root.children().next().unwrap(),&mut warnings),"retained");assert_eq!(warnings.len(),1)}
#[test]fn epub_spine_images_and_footnotes(){let t=common::Temp::new();let d=common::extract(&t.write("a.epub",&common::epub()));let s=render::markdown::render_markdown(&d,false);assert!(s.find("First chapter").unwrap()<s.find("Last chapter").unwrap());assert_eq!(d.assets.len(),1);assert_eq!(d.footnotes.len(),1);assert!(s.contains("[^ch1-n]"));assert_eq!(d.meta.chapter_count,Some(2));assert_eq!(render::choose_output(&d,FormatChoice::Auto).0,render::OutFormat::Md)}
#[test]fn odt_style_merge_and_note(){let t=common::Temp::new();let d=common::extract(&t.write("a.odt",&common::odt()));let s=render::markdown::render_markdown(&d,false);assert!(s.contains("**Bold text**"));assert_eq!(d.footnotes.len(),1);let table=d.blocks.iter().find_map(|b|if let Block::Table(t)=b{Some(t)}else{None}).unwrap();assert_eq!(table.header.len(),1);assert_eq!(table.header[0].colspan,2)}
#[test]fn rtf_style_scope_and_unicode(){let t=common::Temp::new();let d=common::extract(&t.write("a.rtf",br"{\rtf1\ansi plain {\b bold} plain \u233? \'80\par}"));let s=render::markdown::render_markdown(&d,false);assert!(s.contains("**bold**"));assert!(s.contains('é'));assert!(s.contains('€'))}
#[test]fn rtf_malformed_battery(){let t=common::Temp::new();for(i,s)in ["{\\rtf1", "{\\rtf1 \\'", "{\\rtf1 \\'a", "{\\rtf1 \\b", "{\\rtf1 }}}", "{\\rtf1 {", "{\\rtf1 \\u", "{\\rtf1 \\u-1?", "{\\rtf1 \\unknown", "{\\rtf1 \\pict x", "{\\rtf1 \\field", "{\\rtf1 \\ansi", "{\\rtf1 \\bin9999", "{\\rtf1 \\super", "{\\rtf1 \\sub"].iter().enumerate(){let _=common::extract(&t.write(&format!("{i}.rtf"),s.as_bytes()));}let deep=format!("{{\\rtf1 {}text","{".repeat(200));let d=common::extract(&t.write("deep.rtf",deep.as_bytes()));assert!(!d.warnings.is_empty())}
#[test]fn phase1_all_formats_cli_pipeline(){let t=common::Temp::new();for(name,bytes)in[("doc.docx",common::docx("<w:p><w:r><w:t>Hello</w:t></w:r></w:p>")),("book.epub",common::epub()),("odf.odt",common::odt()),("rich.rtf",br"{\rtf1 hello}".to_vec())]{let p=t.write(name,&bytes);let o=Options{format_choice:FormatChoice::Md,output:Some(t.0.join("out")),..Options::default()};let r=convert::convert_file(&p,&o).unwrap();assert!(r.error.is_none());assert!(serde_json::from_str::<serde_json::Value>(&r.to_json().unwrap()).is_ok())}}
#[test]fn rtf_table_hyperlink_and_picture(){let t=common::Temp::new();let d=common::extract(&t.write("rich.rtf",br#"{\rtf1 {\field{\*\fldinst HYPERLINK "https://example.org"}{\fldrslt Link}}\par\trowd A\cell B\cell\row\trowd 1\cell 2\cell\row{\pict\pngblip 89504e470d0a1a0a}}"#));assert!(d.blocks.iter().any(|b|matches!(b,Block::Table(_))));assert_eq!(d.assets.len(),1);assert!(render::markdown::render_markdown(&d,false).contains("https://example.org"))}
#[test]fn phase1_preview_counts_and_docx_txt(){// P1-S06: --preview-equivalent counts per format + DOCX→txt strips structure sensibly.
let t=common::Temp::new();
let body=r#"<w:p><w:pPr><w:pStyle w:val="Haupt"/></w:pPr><w:r><w:t>Title</w:t></w:r></w:p><w:p><w:r><w:drawing><a:blip r:embed="img"/></w:drawing></w:r></w:p><w:p><w:r><w:t>Body</w:t><w:footnoteReference w:id="1"/></w:r></w:p>"#;
let p=t.write("a.docx",&common::docx(body));
let summary=convert::preview(&p,&Options::default()).unwrap();
assert!(summary.contains("docx"));assert!(summary.contains("Footnotes:"));assert!(summary.contains("Images:"));
let o=Options{format_choice:FormatChoice::Txt,output:Some(t.0.join("out")),..Options::default()};
convert::convert_file(&p,&o).unwrap();
let txt=std::fs::read_to_string(t.0.join("out/a.txt")).unwrap();assert!(txt.contains("TITLE"))}
