mod common;
use docconvert::{assets::AssetManager,config::Options,extract::{pdf,ExtractCtx},error::ConvertError,model::*};
fn flat(bytes:&[u8],opts:&Options)->docconvert::error::Result<Document>{let mut assets=AssetManager::default();let mut warnings=vec![];pdf::extract_pdf_flat(bytes,&mut ExtractCtx{options:opts,assets:&mut assets,warnings:&mut warnings})}
#[test]fn prose_pdf_decodes(){let bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (Ordinary PDF prose.) Tj ET"]);let d=flat(&bytes,&Options::default()).unwrap();assert_eq!(d.meta.page_count,Some(1));assert!(d.text_len()>10);assert_eq!(docconvert::render::txt::render_txt(&d).trim(),include_str!("golden/pdf-flat.txt").trim());assert!(d.blocks.iter().any(|b|matches!(b,Block::Paragraph(_))));}
#[test]fn default_columns_disclose_approximation(){let bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (Left first.) Tj 300 0 Td (Right first.) Tj -300 -20 Td (Left last.) Tj ET"]);let d=flat(&bytes,&Options::default()).unwrap();assert!(d.warnings.iter().any(|w|w==pdf::APPROXIMATE));/* Decoder object order deliberately interleaves columns; layout must reorder geometrically. */}
#[test]fn scanned_default_preserved(){let bytes=common::pdf_streams(&["0 0 0 rg 10 10 100 100 re f"]);let opts=Options{ocr_mode:docconvert::config::OcrMode::Auto,..Options::default()};let d=flat(&bytes,&opts).unwrap();assert!(d.blocks.iter().any(|b|matches!(b,Block::Placeholder{kind:PlaceholderKind::ScannedPage,..})));assert!(d.warnings.iter().any(|w|w==pdf::OCR_BUILD));}
#[test]fn scanned_force_default_still_placeholder(){let bytes=common::pdf_streams(&["0 0 0 rg 10 10 100 100 re f"]);let opts=Options{ocr_mode:docconvert::config::OcrMode::Force,..Options::default()};let d=flat(&bytes,&opts).unwrap();assert!(d.blocks.iter().any(|b|matches!(b,Block::Placeholder{kind:PlaceholderKind::ScannedPage,..})));assert!(d.blocks.iter().any(|b|matches!(b,Block::Boundary(Boundary::Page(_)))));assert!(d.warnings.iter().any(|w|w==pdf::OCR_BUILD));}
#[test]fn truncated_pdf_exact_error(){assert!(matches!(flat(b"%PDF-1.4\n",&Options::default()),Err(ConvertError::Corrupt(s))if s=="PDF structure could not be loaded"));}
#[test]fn encrypted_pdf_exact_error(){let mut bytes=common::pdf_streams(&[""]);bytes.extend(b"\n/Encrypt 9 0 R\n");assert!(matches!(flat(&bytes,&Options::default()),Err(ConvertError::Encrypted(s))if s=="password-protected PDF is not supported"));}
#[test]fn clean_text_pdf_force_no_ocr_warning(){let bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (Generated prose.) Tj ET"]);let opts=Options{ocr_mode:docconvert::config::OcrMode::Force,..Options::default()};let d=flat(&bytes,&opts).unwrap();assert!(!d.warnings.iter().any(|w| w==pdf::OCR_BUILD));}
#[test]fn scanned_pdf_convert_file_succeeds_with_placeholders(){// P4-S03 at the convert_file seam: honestly-reported placeholders are a success (exit 0 shape).
let t=common::Temp::new();let p=t.write("scan.pdf",&common::pdf_streams(&["0 0 0 rg 10 10 100 100 re f"]));let o=Options{output:Some(t.0.join("out")),..Options::default()};let r=docconvert::convert::convert_file(&p,&o).unwrap();assert!(r.warnings.iter().any(|w|w.contains("need OCR")||w.contains("needs OCR")));assert!(t.0.join("out/scan.md").exists()||t.0.join("out/scan.txt").exists());}
#[test]fn encrypted_pdf_convert_file_fails_without_partial_output(){// P4-S03: Encrypted → clean error, non-zero-exit shape, no partial output file written.
let t=common::Temp::new();let mut bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (secret) Tj ET"]);bytes.extend(b"\n/Encrypt 9 0 R\n");let p=t.write("enc.pdf",&bytes);let o=Options{output:Some(t.0.join("out")),..Options::default()};assert!(matches!(docconvert::convert::convert_file(&p,&o),Err(ConvertError::Encrypted(_))));assert!(!t.0.join("out/enc.md").exists());assert!(!t.0.join("out/enc.txt").exists());}
fn pdf_with_font(font:&str,stream:&str)->Vec<u8>{let objects=vec![b"<< /Type /Catalog /Pages 2 0 R >>".to_vec(),b"<< /Type /Pages /Count 1 /Kids [4 0 R] >>".to_vec(),font.as_bytes().to_vec(),format!("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 800] /Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R >>").into_bytes(),format!("<< /Length {} >>\nstream\n{}\nendstream",stream.len(),stream).into_bytes()];let mut out=b"%PDF-1.4\n".to_vec();let mut offsets=vec![0];for(i,object)in objects.iter().enumerate(){offsets.push(out.len());out.extend(format!("{} 0 obj\n",i+1).as_bytes());out.extend(object);out.extend(b"\nendobj\n")}let xref=out.len();out.extend(format!("xref\n0 {}\n0000000000 65535 f \n",offsets.len()).as_bytes());for off in &offsets[1..]{out.extend(format!("{off:010} 00000 n \n").as_bytes())}out.extend(format!("trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n",offsets.len()).as_bytes());out}
#[test]fn malformed_font_panic_is_contained(){let bytes=pdf_with_font("<< /Type /Font /Subtype /Type1 >>","BT /F1 12 Tf 30 700 Td (Hi.) Tj ET");assert!(std::panic::catch_unwind(||pdf_extract::extract_text_from_mem(&bytes)).is_err());assert!(matches!(flat(&bytes,&Options::default()),Err(ConvertError::Corrupt(s))if s=="PDF text could not be decoded"));}
#[cfg(feature="pdf-layout")]
#[test]fn missing_pdfium_is_actionable(){let bytes=common::pdf_streams(&["BT /F1 12 Tf 10 10 Td (Hello.) Tj ET"]);let t=common::Temp::new();let opts=Options{pdfium_lib_path:Some(t.0.join("missing-library")),..Options::default()};let mut a=AssetManager::default();let mut w=vec![];let error=pdf::extract_pdf(&bytes,&mut ExtractCtx{options:&opts,assets:&mut a,warnings:&mut w}).unwrap_err();assert!(matches!(error,ConvertError::Config(s)if s.contains("Set PDFIUM_DYNAMIC_LIB_PATH or --pdfium-lib-path")));}
#[cfg(feature="pdf-layout")]
#[test]fn layout_encrypted_reports_encrypted(){// A12/P4-S04: password PDFs surface as Encrypted under layout too (preflight +
// PDFium-refusal mapping share one variant); needs no native library.
let mut bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (secret) Tj ET"]);bytes.extend(b"\n/Encrypt 9 0 R\n");let mut a=AssetManager::default();let mut w=vec![];assert!(matches!(pdf::extract_pdf(&bytes,&mut ExtractCtx{options:&Options::default(),assets:&mut a,warnings:&mut w}),Err(ConvertError::Encrypted(_))));}
#[cfg(feature="pdf-layout")]
#[test]fn native_layout_prose_and_scanned_ocr(){// Intentionally NOT ignored: a layout test run requires native PDFium.
let t=common::Temp::new();let engine=common::fake_ocr(&t.0);let bytes=common::pdf_streams(&["BT /F1 12 Tf 30 700 Td (Ordinary PDF prose.) Tj ET","0 0 0 rg 10 10 100 100 re f"]);let opts=Options{ocr_mode:docconvert::config::OcrMode::Auto,ocr_command:engine.to_string_lossy().into_owned(),..Options::default()};let mut a=AssetManager::default();let mut w=vec![];let d=pdf::extract_pdf(&bytes,&mut ExtractCtx{options:&opts,assets:&mut a,warnings:&mut w}).unwrap();assert_eq!(d.meta.page_count,Some(2));assert!(d.blocks.iter().any(|b|matches!(b,Block::Paragraph(xs)if inline_text(xs).contains("OCR fixture text"))));}
