use super::{package::{self,Content,Element,Package},ExtractCtx};
use crate::{error::Result,model::*};
use std::collections::{HashMap,HashSet};
pub fn extract_odt(bytes:&[u8],ctx:&mut ExtractCtx<'_>)->Result<Document>{let pkg=Package::open(bytes)?;let root=pkg.xml("content.xml")?;let mut d=Document::default();if let Ok(meta)=pkg.xml("meta.xml"){d.meta.title=meta.desc("title").next().map(|n|n.text());d.meta.author=meta.desc("creator").next().map(|n|n.text());d.meta.language=meta.desc("language").next().map(|n|n.text());}
 let mut defs=HashMap::new();for r in [pkg.optional_xml("styles.xml",ctx.warnings),Some(root.clone())].into_iter().flatten(){for n in r.desc("style"){defs.insert(n.attr("name").to_owned(),n);}}
 let mut styles=HashMap::new();for key in defs.keys(){let mut chain=vec![];let mut seen=HashSet::new();let mut k=key.as_str();while let Some(n)=defs.get(k){if !seen.insert(k.to_owned()){ctx.warnings.push("ODF style inheritance cycle ignored".into());break}chain.push(n);k=n.attr("parent-style-name");}let mut style=TextStyle::default();for n in chain.iter().rev(){if let Some(p)=n.child("text-properties"){match p.attr("font-weight"){"bold"=>style.bold=true,"normal"=>style.bold=false,_=>{}}match p.attr("font-style"){"italic"=>style.italic=true,"normal"=>style.italic=false,_=>{}}}}styles.insert(key.clone(),style);}
 let mut lists=HashMap::new();for n in root.desc("list-style"){for level in n.children(){lists.insert((n.attr("name").to_owned(),level.attr("level").parse::<usize>().unwrap_or(1)),package::local(&level.name)=="list-level-style-number");}}
 fn inline(n:&Element,styles:&HashMap<String,TextStyle>,notes:&mut Vec<(String,Vec<Inline>)>)->Vec<Inline>{let mut out=vec![];for c in n.content(){match c{Content::Text(s)=>out.push(Inline::Text(s.clone())),Content::Element(e)=>{let tag=package::local(&e.name);if tag=="note"{let id=e.child("note-citation").map(|n|n.text()).unwrap_or_else(||format!("{}",notes.len()+1));let val=e.child("note-body").map(|n|inline(&n,styles,notes)).unwrap_or_default();notes.push((id.clone(),val));out.push(Inline::FootnoteRef(id));continue}let children=inline(&e,styles,notes);match tag{"span"=>{let style=styles.get(e.attr("style-name")).cloned().unwrap_or_default();out.push(Inline::Styled{style,children})},"a"=>out.push(Inline::Link{url:e.attr("href").into(),children}),"line-break"=>out.push(Inline::Break),"tab"=>out.push(Inline::Text("\t".into())),"s"=>out.push(Inline::Text(" ".repeat(e.attr("c").parse::<usize>().unwrap_or(1).min(10000)))),"image"=>{},_=>out.extend(children)}}}}out}
 struct Walker<'a,'b,'c>{pkg:&'a Package,styles:&'a HashMap<String,TextStyle>,lists:&'a HashMap<(String,usize),bool>,ctx:&'b mut ExtractCtx<'c>}
 impl Walker<'_, '_, '_>{fn blocks(&mut self,n:&Element,notes:&mut Vec<(String,Vec<Inline>)>,level:usize,list_style:&str)->Vec<Block>{let mut out=vec![];for e in n.children(){match package::local(&e.name){"h"=>out.push(Block::Heading{level:e.attr("outline-level").parse::<usize>().unwrap_or(1).clamp(1,6),inlines:inline(&e,self.styles,notes)}),"p"=>{let xs=inline(&e,self.styles,notes);if !inline_text(&xs).trim().is_empty(){out.push(Block::Paragraph(xs))}for image in e.desc("image"){self.image(&image,&mut out)}},"list"=>{let style=if e.attr("style-name").is_empty(){list_style}else{e.attr("style-name")};let ordered=*self.lists.get(&(style.into(),level+1)).unwrap_or(&false);let mut items=vec![];for li in e.children().filter(|n|package::local(&n.name)=="list-item"){items.push(ListItem{level,blocks:self.blocks(&li,notes,level+1,style)})}out.push(Block::List{ordered,start:ordered.then_some(1),items})},"table"=>{let mut rows=vec![];for r in e.desc("table-row"){let mut cells=vec![];for c in r.children().filter(|n|package::local(&n.name)=="table-cell"){cells.push(TableCell{inlines:inline(&c,self.styles,notes),colspan:c.attr("number-columns-spanned").parse::<usize>().unwrap_or(1).clamp(1,1000),rowspan:c.attr("number-rows-spanned").parse::<usize>().unwrap_or(1).clamp(1,1000),align:Align::Default})}rows.push(cells)}let header=if rows.is_empty(){vec![]}else{rows.remove(0)};out.push(Block::Table(Table{header,rows,..Table::default()}))},"image"=>self.image(&e,&mut out),_=>out.extend(self.blocks(&e,notes,level,list_style))}}out}
 fn image(&mut self,e:&Element,out:&mut Vec<Block>){if let Some(name)=package::normalize("",e.attr("href")){if let Some(b)=self.pkg.get(&name){let asset=self.ctx.assets.add(b.to_vec(),"ODF image",None);out.push(Block::Image{asset,alt:None,caption:None});return}}self.ctx.warnings.push("ODF image missing or unsafe".into())}}
 let mut walker=Walker{pkg:&pkg,styles:&styles,lists:&lists,ctx};d.blocks=walker.blocks(&root,&mut d.footnotes,0,"");Ok(d)}
