[package]
name = "docconvert-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.docconvert]
path = ".."

[[bin]]
name = "fuzz_rtf"
path = "fuzz_targets/fuzz_rtf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_pdf"
path = "fuzz_targets/fuzz_pdf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_csv"
path = "fuzz_targets/fuzz_csv.rs"
test = false
doc = false
bench = false
