use crate::model::*;
use base64::Engine;
fn escape(s:&str)->String{let mut out=String::new();for c in s.chars(){if "\\*_`[]<>|#!".contains(c){out.push('\\')}out.push(c)}out}
fn code(s:&str)->String{let n=s.split(|c|c!='`').map(str::len).max().unwrap_or(0)+1;let fence="`".repeat(n.max(1));if s.starts_with('`')||s.ends_with('`'){format!("{fence} {s} {fence}")}else{format!("{fence}{s}{fence}")}}
fn image(doc:&Document,id:usize,alt:&Option<String>,embed:bool)->String{if let Some(a)=doc.assets.get(id){let url=if embed{format!("data:{};base64,{}",a.mime,base64::engine::general_purpose::STANDARD.encode(&a.bytes))}else{a.rel_path.clone()};format!("![{}]({})",escape(alt.as_deref().or(a.alt.as_deref()).unwrap_or("")),url.replace(')',"%29"))}else{"[Image unavailable]".into()}}
fn inline(xs:&[Inline],doc:&Document,embed:bool)->String{let mut out=String::new();for i in xs{out.push_str(&match i{Inline::Text(s)=>escape(s),Inline::Styled{style,children}=>{let mut s=inline(children,doc,embed);if style.strike{s=format!("~~{s}~~")}if style.italic{s=format!("*{s}*")}if style.bold{s=format!("**{s}**")}s},Inline::Code(s)=>code(s),Inline::Link{children,url}=>if url.is_empty(){inline(children,doc,embed)}else{format!("[{}]({})",inline(children,doc,embed),url.replace(')',"%29").replace('\n',"%0A"))},Inline::MathInline(s)=>format!("${s}$"),Inline::FootnoteRef(id)=>format!("[^{}]",escape(id)),Inline::Image{asset,alt}=>image(doc,*asset,alt,embed),Inline::Break=>"  \n".into()})}out}
fn cell(c:&TableCell,doc:&Document,embed:bool)->String{let raw=inline(&c.inlines,doc,embed).replace('\n'," ");let mut out=String::new();let mut slashes=0;for ch in raw.chars(){if ch=='|'&&slashes%2==0{out.push('\\')}out.push(ch);if ch=='\\'{slashes+=1}else{slashes=0}}out}
fn blocks(bs:&[Block],doc:&Document,embed:bool)->String{let mut out=String::new();for b in bs{let s=match b{
 Block::Heading{level,inlines}=>format!("{} {}", "#".repeat((*level).clamp(1,6)),inline(inlines,doc,embed)),Block::Paragraph(xs)=>inline(xs,doc,embed),
 Block::List{ordered,start,items}=>items.iter().enumerate().map(|(i,item)|{let marker=if *ordered{format!("{}.",start.unwrap_or(1)+i as u64)}else{"-".into()};let content=blocks(&item.blocks,doc,embed);let mut ls=content.trim_end().lines();let first=ls.next().unwrap_or("");let indent=" ".repeat(item.level.min(64)*2);let mut s=format!("{indent}{marker} {first}");for l in ls{let leading=l.len()-l.trim_start().len();let nested=leading>=indent.len()+2&&(l.trim_start().starts_with("- ")||l.trim_start().chars().next().map(|c|c.is_ascii_digit()).unwrap_or(false));if nested{s.push_str(&format!("\n{l}"))}else{s.push_str(&format!("\n{indent}  {l}"))}}s}).collect::<Vec<_>>().join("\n"),
 Block::Table(t)=>{let rows=super::expanded_rows(t);let width=rows.first().map(Vec::len).unwrap_or(0);let mut s=String::new();if t.approximate{s.push_str("<!-- approximate reconstruction -->\n")}let serialize=|row:&[TableCell]|format!("| {} |",row.iter().map(|c|cell(c,doc,embed)).collect::<Vec<_>>().join(" | "));let header=rows.first().cloned().unwrap_or_default();s.push_str(&serialize(&header));s.push('\n');let sep=header.iter().map(|c|match c.align{Align::Left=>":---",Align::Right=>"---:",Align::Center=>":---:",_=>"---"}).collect::<Vec<_>>();if width>0{s.push_str(&format!("| {} |",sep.join(" | ")))}for row in rows.iter().skip(1){s.push('\n');s.push_str(&serialize(row))}if let Some(c)=&t.caption{s.push_str(&format!("\n\n*{}*",escape(c)))}s},
 Block::CodeBlock{language,text}=>{let longest=text.split(|c|c!='`').map(str::len).max().unwrap_or(0);let fence="`".repeat((longest+1).max(3));format!("{fence}{}\n{text}\n{fence}",language.as_deref().unwrap_or("").replace(['\n','\r','`'],""))},Block::MathBlock(s)=>format!("$$\n{s}\n$$"),Block::Quote(bs)=>blocks(bs,doc,embed).trim_end().lines().map(|s|format!("> {s}")).collect::<Vec<_>>().join("\n"),Block::Rule=>"---".into(),
 Block::Image{asset,alt,caption}=>{let mut s=image(doc,*asset,alt,embed);if let Some(c)=caption{s.push_str(&format!("\n\n*{}*",escape(c)))}s},Block::Placeholder{kind,label,asset}=>if let Some(id)=asset{image(doc,*id,label,embed)}else{format!("> [{}{} — no rendered asset available]",kind.label(),label.as_ref().map(|s|format!(": {}",escape(s))).unwrap_or_default())},
 Block::Boundary(Boundary::Page(n))=>format!("<!-- page {n} -->"),Block::Boundary(Boundary::Chapter(_))=>"---".into(),Block::Boundary(_)=>String::new(),Block::FormulaList(fs)=>format!("### Formulas\n\n{}",fs.iter().map(|(r,f)|format!("- {}",code(&format!("{r} {}",if f.starts_with('='){f.clone()}else{format!("= {f}")})))).collect::<Vec<_>>().join("\n")),
 };if !s.is_empty(){out.push_str(s.trim_matches('\n'));out.push_str("\n\n")}}out}
pub fn render_markdown(doc:&Document,embed_assets:bool)->String{let mut s=blocks(&doc.blocks,doc,embed_assets);for(id,xs)in &doc.footnotes{s.push_str(&format!("[^{}]: {}\n",escape(id),inline(xs,doc,embed_assets).replace('\n'," ")))}while s.ends_with('\n'){s.pop();}s.push('\n');s}
