#![allow(dead_code)]
use std::{fs,io::{Cursor,Write},path::{Path,PathBuf},sync::atomic::{AtomicU64,Ordering}};
static COUNTER:AtomicU64=AtomicU64::new(0);
pub struct Temp(pub PathBuf);
impl Temp {pub fn new()->Self{loop{let n=COUNTER.fetch_add(1,Ordering::Relaxed);let path=std::env::temp_dir().join(format!("docconvert-test-{}-{n}",std::process::id()));match fs::create_dir(&path){Ok(())=>return Self(path),Err(e)if e.kind()==std::io::ErrorKind::AlreadyExists=>continue,Err(e)=>panic!("test temp directory: {e}")}}}pub fn write(&self,name:&str,bytes:&[u8])->PathBuf{let path=self.0.join(name);fs::create_dir_all(path.parent().unwrap()).unwrap();fs::write(&path,bytes).unwrap();path}}
impl Drop for Temp{fn drop(&mut self){let _=fs::remove_dir_all(&self.0);}}
pub fn zip(parts:&[(&str,&[u8])])->Vec<u8>{let mut writer=zip::ZipWriter::new(Cursor::new(Vec::new()));for(name,data)in parts{writer.start_file(*name,zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored)).unwrap();writer.write_all(data).unwrap()}writer.finish().unwrap().into_inner()}
pub fn png()->Vec<u8>{// Minimal PNG signature + IHDR fixture: asset handling does not decode pixels.
 b"\x89PNG\r\n\x1a\n\0\0\0\rIHDR\0\0\0\x01\0\0\0\x01\x08\x02\0\0\0".to_vec()}
pub fn docx(body:&str)->Vec<u8>{let document=format!(r#"<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><w:body>{body}</w:body></w:document>"#);let image=png();zip(&[
 ("[Content_Types].xml",b"<Types/>"),("word/document.xml",document.as_bytes()),
 ("word/styles.xml",br#"<w:styles xmlns:w="w"><w:style w:styleId="Haupt"><w:name w:val="Titel"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr></w:style></w:styles>"#),
 ("word/numbering.xml",br#"<w:numbering xmlns:w="w"><w:abstractNum w:abstractNumId="7"><w:lvl w:ilvl="0"><w:start w:val="3"/><w:numFmt w:val="decimal"/></w:lvl><w:lvl w:ilvl="1"><w:numFmt w:val="bullet"/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="7"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="7"/></w:num></w:numbering>"#),
 ("word/_rels/document.xml.rels",br#"<Relationships><Relationship Id="img" Type="image" Target="media/a.png"/><Relationship Id="url" Type="hyperlink" Target="https://example.org" TargetMode="External"/></Relationships>"#),
 ("word/media/a.png",&image),("word/footnotes.xml",br#"<w:footnotes xmlns:w="w"><w:footnote w:id="-1" w:type="separator"/><w:footnote w:id="1"><w:p><w:r><w:t>Footnote text</w:t></w:r></w:p></w:footnote></w:footnotes>"#),
 ])}
pub fn epub()->Vec<u8>{let image=png();zip(&[
 ("mimetype",b"application/epub+zip"),("META-INF/container.xml",br#"<container><rootfiles><rootfile full-path="OEBPS/package.opf"/></rootfiles></container>"#),
 ("OEBPS/package.opf",br#"<package><metadata><title>Book</title><creator>Author</creator></metadata><manifest><item id="a" href="text/a.xhtml" media-type="application/xhtml+xml"/><item id="b" href="text/b.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="b"/><itemref idref="a"/></spine></package>"#),
 ("OEBPS/text/a.xhtml",br#"<html><body><h1>Last chapter</h1></body></html>"#),
 ("OEBPS/text/b.xhtml",br##"<html xmlns:epub="epub"><body><h1>First chapter</h1><p>A note <a href="#n">1</a></p><img src="../images/p.png" alt="Picture"/><aside epub:type="footnote" id="n"><p>Note content</p></aside></body></html>"##),
 ("OEBPS/images/p.png",&image)])}
pub fn odt()->Vec<u8>{zip(&[("mimetype",b"application/vnd.oasis.opendocument.text"),("styles.xml",br#"<styles><style:style xmlns:style="s" xmlns:fo="f" style:name="Base"><style:text-properties fo:font-weight="bold"/></style:style><style:style xmlns:style="s" style:name="Child" style:parent-style-name="Base"/></styles>"#),("content.xml",br#"<office:document-content xmlns:office="o" xmlns:text="t" xmlns:table="ta"><office:body><office:text><text:h text:outline-level="2">ODT heading</text:h><text:p><text:span text:style-name="Child">Bold text</text:span><text:note text:note-class="footnote"><text:note-citation>1</text:note-citation><text:note-body><text:p>ODT note</text:p></text:note-body></text:note></text:p><table:table><table:table-row><table:table-cell table:number-columns-spanned="2"><text:p>Merged</text:p></table:table-cell><table:covered-table-cell/></table:table-row></table:table></office:text></office:body></office:document-content>"#)])}
pub fn pptx()->Vec<u8>{let image=png();zip(&[
 ("[Content_Types].xml",b"<Types/>"),("ppt/presentation.xml",br#"<p:presentation xmlns:p="p" xmlns:r="r"><p:sldIdLst><p:sldId id="256" r:id="r7"/><p:sldId id="257" r:id="r2"/></p:sldIdLst></p:presentation>"#),
 ("ppt/_rels/presentation.xml.rels",br#"<Relationships><Relationship Id="r7" Target="slides/slide7.xml"/><Relationship Id="r2" Target="slides/slide2.xml"/></Relationships>"#),
 ("ppt/slides/slide7.xml",br#"<p:sld xmlns:p="p" xmlns:a="a" xmlns:r="r"><p:cSld><p:spTree><p:sp><p:nvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr><p:txBody><a:p><a:r><a:t>First slide</a:t></a:r></a:p></p:txBody></p:sp><p:sp><p:txBody><a:p><a:pPr lvl="1"><a:buChar char="-"/></a:pPr><a:r><a:t>Nested bullet</a:t></a:r></a:p></p:txBody></p:sp><p:pic><p:blipFill><a:blip r:embed="image1"/></p:blipFill></p:pic></p:spTree></p:cSld></p:sld>"#),
 ("ppt/slides/slide2.xml",br#"<p:sld xmlns:p="p" xmlns:a="a"><p:cSld><p:spTree><p:sp><p:nvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr><p:txBody><a:p><a:r><a:t>Last slide</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>"#),
 ("ppt/slides/_rels/slide7.xml.rels",br#"<Relationships><Relationship Id="image1" Target="../media/p.png" Type="image"/><Relationship Id="notes" Target="../notesSlides/notesSlide9.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide"/></Relationships>"#),
 ("ppt/notesSlides/notesSlide9.xml",br#"<p:notes xmlns:p="p" xmlns:a="a"><p:sp><p:nvSpPr><p:nvPr><p:ph type="body"/></p:nvPr></p:nvSpPr><p:txBody><a:p><a:r><a:t>Private speaker note</a:t></a:r></a:p></p:txBody></p:sp></p:notes>"#),
 ("ppt/media/p.png",&image)])}
pub fn xlsx()->Vec<u8>{zip(&[
 ("[Content_Types].xml",br#"<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>"#),
 ("_rels/.rels",br#"<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>"#),
 ("xl/workbook.xml",br#"<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Data" sheetId="1" r:id="s1"/><sheet name="Hidden" sheetId="2" state="hidden" r:id="s2"/></sheets></workbook>"#),
 ("xl/_rels/workbook.xml.rels",br#"<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="s1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet8.xml"/><Relationship Id="s2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/></Relationships>"#),
 ("xl/worksheets/sheet8.xml",br#"<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:D1000000"/><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Total</t></is></c></row><row r="2"><c r="B2"><v>100000</v></c><c r="D2"><f>SUM(B2:B3)</f><v>220000</v></c></row><row r="3"><c r="B3"><v>120000</v></c></row></sheetData><mergeCells><mergeCell ref="A1:B1"/></mergeCells><hyperlinks><hyperlink ref="A1" r:id="link"/></hyperlinks></worksheet>"#),
 ("xl/worksheets/_rels/sheet8.xml.rels",br#"<Relationships><Relationship Id="link" Type="hyperlink" Target="https://example.org" TargetMode="External"/><Relationship Id="comment" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/></Relationships>"#),
 ("xl/comments1.xml",br#"<comments><commentList><comment ref="D2"><text><t>Formula comment</t></text></comment></commentList></comments>"#),
 ("xl/worksheets/sheet2.xml",br#"<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Secret sheet text</t></is></c></row></sheetData></worksheet>"#),
 ])}
pub fn ods()->Vec<u8>{zip(&[("mimetype",b"application/vnd.oasis.opendocument.spreadsheet"),("META-INF/manifest.xml",br#"<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/></manifest:manifest>"#),("content.xml",br#"<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2"><office:body><office:spreadsheet><table:table table:name="Data"><table:table-row><table:table-cell office:value-type="string"><text:p>Total</text:p></table:table-cell></table:table-row><table:table-row><table:table-cell office:value-type="float" office:value="3" table:formula="of:=SUM([.B2:.B3])"><text:p>3</text:p></table:table-cell></table:table-row></table:table></office:spreadsheet></office:body></office:document-content>"#)])}
pub fn extract(path:&Path)->docconvert::model::Document{let detection=docconvert::detect::detect_file(path).unwrap();docconvert::extract::extract_file(path,&detection,&docconvert::config::Options::default()).unwrap()}
/// BIFF8 workbook inside a minimal CFB v3 container, built entirely from source.
pub fn xls()->Vec<u8>{
 fn rec(out:&mut Vec<u8>,id:u16,payload:&[u8]){out.extend(id.to_le_bytes());out.extend((payload.len()as u16).to_le_bytes());out.extend(payload)}
 fn bof(kind:u16)->Vec<u8>{let mut p=vec![];p.extend(0x0600u16.to_le_bytes());p.extend(kind.to_le_bytes());p.extend(0x0dbbu16.to_le_bytes());p.extend(0x07ccu16.to_le_bytes());p.extend(0x41u32.to_le_bytes());p.extend(0x06u32.to_le_bytes());p}
 let mut globals=vec![];rec(&mut globals,0x0809,&bof(0x0005));rec(&mut globals,0x0042,&1252u16.to_le_bytes());
 // BOUNDSHEET: stream position follows globals; fixed payload is 8+4-byte name.
 let sheet_offset=(globals.len()+4+12+4)as u32;let mut bound=vec![];bound.extend(sheet_offset.to_le_bytes());bound.extend([0,0,4,0]);bound.extend(b"Data");rec(&mut globals,0x0085,&bound);rec(&mut globals,0x000a,&[]);
 let mut worksheet=vec![];rec(&mut worksheet,0x0809,&bof(0x0010));let mut dim=vec![];dim.extend(0u32.to_le_bytes());dim.extend(1u32.to_le_bytes());dim.extend(0u16.to_le_bytes());dim.extend(1u16.to_le_bytes());dim.extend(0u16.to_le_bytes());rec(&mut worksheet,0x0200,&dim);
 let mut formula=vec![0;6];formula.extend(3f64.to_le_bytes());formula.extend([0;6]);let tokens=[0x1e,1,0,0x1e,2,0,0x03];formula.extend((tokens.len()as u16).to_le_bytes());formula.extend(tokens);rec(&mut worksheet,0x0006,&formula);rec(&mut worksheet,0x000a,&[]);globals.extend(worksheet);globals.resize(4096,0);
 const FREE:u32=0xffff_ffff;const END:u32=0xffff_fffe;const FAT:u32=0xffff_fffd;
 let mut header=vec![0u8;512];header[..8].copy_from_slice(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1");header[24..26].copy_from_slice(&0x003eu16.to_le_bytes());header[26..28].copy_from_slice(&3u16.to_le_bytes());header[28..30].copy_from_slice(&0xfffeu16.to_le_bytes());header[30..32].copy_from_slice(&9u16.to_le_bytes());header[32..34].copy_from_slice(&6u16.to_le_bytes());header[44..48].copy_from_slice(&1u32.to_le_bytes());header[48..52].copy_from_slice(&8u32.to_le_bytes());header[56..60].copy_from_slice(&4096u32.to_le_bytes());header[60..64].copy_from_slice(&END.to_le_bytes());header[68..72].copy_from_slice(&END.to_le_bytes());for i in 0..109{header[76+i*4..80+i*4].copy_from_slice(&FREE.to_le_bytes())}header[76..80].copy_from_slice(&9u32.to_le_bytes());
 fn entry(name:&str,kind:u8,start:u32,size:u64,child:u32)->Vec<u8>{let mut e=vec![0u8;128];let name=name.encode_utf16().chain(std::iter::once(0)).collect::<Vec<_>>();for(i,c)in name.iter().enumerate(){e[i*2..i*2+2].copy_from_slice(&c.to_le_bytes())}e[64..66].copy_from_slice(&((name.len()*2)as u16).to_le_bytes());e[66]=kind;e[67]=1;e[68..72].copy_from_slice(&0xffff_ffffu32.to_le_bytes());e[72..76].copy_from_slice(&0xffff_ffffu32.to_le_bytes());e[76..80].copy_from_slice(&child.to_le_bytes());e[116..120].copy_from_slice(&start.to_le_bytes());e[120..128].copy_from_slice(&size.to_le_bytes());e}
 let mut directory=entry("Root Entry",5,END,0,1);directory.extend(entry("Workbook",2,0,4096,FREE));directory.resize(512,0);let mut fat=vec![];for i in 0..128u32{fat.extend(match i{0..=6=>i+1,7|8=>END,9=>FAT,_=>FREE}.to_le_bytes())}header.extend(globals);header.extend(directory);header.extend(fat);header
}

pub fn zip_patch(bytes:&[u8],changes:&[(&str,&[u8])])->Vec<u8>{
    use std::io::Read;
    let mut archive=zip::ZipArchive::new(Cursor::new(bytes)).unwrap();
    let mut parts=std::collections::BTreeMap::new();
    for i in 0..archive.len(){let mut member=archive.by_index(i).unwrap();if member.is_dir(){continue}let name=member.name().to_owned();let mut data=vec![];member.read_to_end(&mut data).unwrap();parts.insert(name,data);}
    for(name,data)in changes{parts.insert((*name).into(),data.to_vec());}
    let refs:Vec<_>=parts.iter().map(|(name,data)|(name.as_str(),data.as_slice())).collect();zip(&refs)
}

/// Minimal uncompressed PDF, generated from text streams with a real xref table.
pub fn pdf_streams(streams:&[&str])->Vec<u8>{let mut objects=vec![b"<< /Type /Catalog /Pages 2 0 R >>".to_vec(),vec![],b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_vec()];let mut kids=vec![];for s in streams{let page=objects.len()+1;let content=page+1;kids.push(format!("{page} 0 R"));objects.push(format!("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 800] /Resources << /Font << /F1 3 0 R >> >> /Contents {content} 0 R >>").into_bytes());objects.push(format!("<< /Length {} >>\nstream\n{}\nendstream",s.len(),s).into_bytes())}objects[1]=format!("<< /Type /Pages /Count {} /Kids [{}] >>",streams.len(),kids.join(" ")).into_bytes();let mut out=b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n".to_vec();let mut offsets=vec![0];for(i,object)in objects.iter().enumerate(){offsets.push(out.len());out.extend(format!("{} 0 obj\n",i+1).as_bytes());out.extend(object);out.extend(b"\nendobj\n")}let xref=out.len();out.extend(format!("xref\n0 {}\n0000000000 65535 f \n",offsets.len()).as_bytes());for off in &offsets[1..]{out.extend(format!("{off:010} 00000 n \n").as_bytes())}out.extend(format!("trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n",offsets.len()).as_bytes());out}
pub fn fake_ocr(dir:&Path)->PathBuf{let binary=dir.join(if cfg!(windows){"fake-ocr.exe"}else{"fake-ocr"});let status=std::process::Command::new("rustc").arg("--edition=2021").arg(concat!(env!("CARGO_MANIFEST_DIR"),"/tests/fixtures/fake-ocr/main.rs")).arg("-o").arg(&binary).status().expect("rustc needed for source-only OCR fixture");assert!(status.success());binary}
