//! Whole-file worker queue. Results are returned in stable expansion order.
use crate::{config::Options,convert::convert_file,detect::expected_formats,error::{ConvertError,Result},report::Report};
use std::{collections::{BTreeSet,VecDeque},path::{Path,PathBuf},sync::Mutex};
pub struct BatchResult{pub reports:Vec<(PathBuf,Result<Report>)>,pub not_started:usize}
struct Job{path:PathBuf,output:Option<PathBuf>,error:Option<ConvertError>}
fn supported(p:&Path)->bool{p.extension().and_then(|s|s.to_str()).map(|s|!expected_formats(&s.to_ascii_lowercase()).is_empty()).unwrap_or(false)}
fn jobs(paths:&[PathBuf],opts:&Options)->Vec<Job>{let mut out=vec![];let mut seen=BTreeSet::new();for root in paths{
    if root.is_dir()&&!root.is_symlink(){let mut entries=vec![];let depth=if opts.recursive{usize::MAX}else{1};for entry in walkdir::WalkDir::new(root).follow_links(false).max_depth(depth).min_depth(1){match entry{Ok(e)if e.file_type().is_file()&&supported(e.path())=>{if opts.output.as_ref().and_then(|p|p.canonicalize().ok()).map(|p|e.path().canonicalize().map(|f|f.starts_with(p)).unwrap_or(false)).unwrap_or(false){continue}entries.push(Job{path:e.path().into(),output:opts.output.as_ref().map(|o|o.join(e.path().strip_prefix(root).unwrap_or(e.path()).parent().unwrap_or(Path::new("")))),error:None})},Ok(_)=>{},Err(e)=>entries.push(Job{path:e.path().unwrap_or(root).into(),output:None,error:Some(ConvertError::Io(std::io::Error::new(e.io_error().map(|e|e.kind()).unwrap_or(std::io::ErrorKind::Other),"directory scan failed")))})}}entries.sort_by(|a,b|a.path.cmp(&b.path));out.extend(entries);
    }else{out.push(Job{path:root.clone(),output:opts.output.clone(),error:if root.is_symlink(){Some(ConvertError::Unsupported("symbolic-link inputs are not followed in batch mode".into()))}else{None}})}
}out.retain(|j|seen.insert(j.path.canonicalize().unwrap_or_else(|_|j.path.clone())));
// Same output stem also shares a report and asset namespace, regardless of selected
// text extension. Reject later collisions before workers can race, even with overwrite.
let mut destinations=BTreeSet::new();for job in &mut out{let dir=job.output.clone().unwrap_or_else(||job.path.parent().unwrap_or(Path::new(".")).into());let key=(dir,job.path.file_stem().unwrap_or_default().to_os_string());if !destinations.insert(key)&&job.error.is_none(){job.error=Some(ConvertError::Output("batch inputs have colliding output stems".into()))}}out}
pub fn expand_inputs(paths:&[PathBuf],recursive:bool)->Vec<std::result::Result<PathBuf,(PathBuf,ConvertError)>>{let opts=Options{recursive,..Options::default()};jobs(paths,&opts).into_iter().map(|j|if let Some(e)=j.error{Err((j.path,e))}else if let Err(e)=std::fs::metadata(&j.path){Err((j.path,e.into()))}else{Ok(j.path)}).collect()}
pub fn convert_batch(inputs:Vec<PathBuf>,opts:&Options)->BatchResult{
    let jobs=jobs(&inputs,opts);let total=jobs.len();let queue=Mutex::new((jobs.into_iter().enumerate().collect::<VecDeque<_>>(),false));let results=Mutex::new(vec![]);let count=if opts.jobs==0{std::thread::available_parallelism().map(|n|n.get()).unwrap_or(1).min(8)}else{opts.jobs.min(256)}.min(total.max(1));
    std::thread::scope(|scope|{for _ in 0..count{let queue=&queue;let results=&results;scope.spawn(move||loop{let next={let mut q=queue.lock().unwrap_or_else(|p|p.into_inner());if q.1{None}else{q.0.pop_front()}};let Some((index,job))=next else{break};let mut options=opts.clone();options.output=job.output;let result=if let Some(e)=job.error{Err(e)}else{std::panic::catch_unwind(std::panic::AssertUnwindSafe(||convert_file(&job.path,&options))).unwrap_or_else(|_|Err(ConvertError::Corrupt("converter panicked while processing input".into())))};if result.is_err()&&opts.strict{queue.lock().unwrap_or_else(|p|p.into_inner()).1=true}results.lock().unwrap_or_else(|p|p.into_inner()).push((index,job.path,result));});}});
    let mut reports=results.into_inner().unwrap_or_else(|p|p.into_inner());reports.sort_by_key(|(i,_,_)|*i);let not_started=total-reports.len();BatchResult{reports:reports.into_iter().map(|(_,p,r)|(p,r)).collect(),not_started}
}
