use crate::{config::Options,detect::Detection,error::{ConvertError,Result},model::*,render::OutFormat};
use serde::Serialize;
#[derive(Debug,Clone,Serialize)]
pub struct Report {pub input:String,pub detected_format:String,pub extension_match:bool,pub output_format:String,pub format_reason:String,pub timestamp:u64,pub duration_ms:u128,pub pages:usize,pub slides:usize,pub chapters:usize,pub worksheets:usize,pub tables:usize,pub images:usize,pub formulas:usize,pub footnotes:usize,pub ocr_status:String,pub pdf_path:Option<String>,pub image_dimensions:Vec<(String,Option<(u32,u32)>)>,pub warnings:Vec<String>,pub error:Option<String>,pub outputs:Vec<String>,pub assets:Vec<String>,pub extractor_version:&'static str,pub config_summary:Vec<String>,pub status:String}
impl Report {
 pub fn from_document(doc:&Document,detection:&Detection,format:OutFormat,reason:String,opts:&Options)->Self{fn count(bs:&[Block])->usize{bs.iter().map(|b|match b{Block::Table(_)=>1,Block::Quote(bs)=>count(bs),Block::List{items,..}=>items.iter().map(|i|count(&i.blocks)).sum(),_=>0}).sum()}
 Self{input:doc.meta.source_filename.clone(),detected_format:detection.format.to_string(),extension_match:detection.extension_match,output_format:format.ext().into(),format_reason:reason,timestamp:std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d|d.as_secs()).unwrap_or(0),duration_ms:0,pages:doc.meta.page_count.unwrap_or(0),slides:doc.meta.slide_count.unwrap_or(0),chapters:doc.meta.chapter_count.unwrap_or(0),worksheets:doc.meta.worksheet_count.unwrap_or(0),tables:count(&doc.blocks),images:doc.assets.len(),formulas:doc.workbook.as_ref().map(|w|w.sheets.iter().flat_map(|s|s.cells.values()).filter(|c|c.formula.is_some()).count()).unwrap_or(0),footnotes:doc.footnotes.len(),ocr_status:if opts.ocr_mode==crate::config::OcrMode::Off{"off"}else if doc.warnings.iter().any(|w|w.starts_with("OCR completed:")){"completed (confidence unavailable)"}else if doc.warnings.iter().any(|w|w.contains("no engine found")){"engine unavailable"}else if doc.warnings.iter().any(|w|w.contains("requires the pdf-layout")){"requires pdf-layout"}else{"not needed"}.into(),pdf_path:if detection.format==Format::Pdf{Some(if cfg!(feature="pdf-layout"){"layout"}else{"default"}.into())}else{None},image_dimensions:doc.assets.iter().map(|a|(a.filename.clone(),crate::detect::image_kind(&a.bytes).and_then(|k|crate::extract::image::read_dimensions(&a.bytes,k)))).collect(),warnings:doc.warnings.clone(),error:None,outputs:vec![],assets:doc.assets.iter().map(|a|a.rel_path.clone()).collect(),extractor_version:env!("CARGO_PKG_VERSION"),config_summary:vec![format!("format={:?}",opts.format_choice),format!("formulas={}",opts.preserve_formulas),format!("comments={}",opts.include_comments),format!("hidden-sheets={}",opts.include_hidden_sheets),format!("notes={}",opts.include_notes)],status:"converted".into()}}
 pub fn to_json(&self)->Result<String>{serde_json::to_string_pretty(self).map_err(|_|ConvertError::Output("report serialization failed".into()))}
 pub fn to_text(&self)->String{let mut text=format!("Input:       {}\nDetected:    {}\nExtension:   {}\nOutput:      {}\nReason:      {}\nStatus:      {}\nPages:       {}\nSlides:      {}\nChapters:    {}\nWorksheets:  {}\nTables:      {}\nImages:      {}\nFormulas:    {}\nFootnotes:   {}\nOCR:         {}\nWarnings:\n{}\n",self.input,self.detected_format,self.extension_match,self.output_format,self.format_reason,self.status,self.pages,self.slides,self.chapters,self.worksheets,self.tables,self.images,self.formulas,self.footnotes,self.ocr_status,self.warnings.iter().map(|s|format!("- {s}")).collect::<Vec<_>>().join("\n"));if let Some(path)=&self.pdf_path{text.push_str(&format!("PDF path:    {path}\n"))}for(name,size)in &self.image_dimensions{text.push_str(&format!("Image:       {name}: {}\n",size.map(|(w,h)|format!("{w} x {h}")).unwrap_or_else(||"dimensions unknown".into())))}text}
}
